export interface KoreanWord {
  korean: string;
  romanization: string;
  english: string;
  partOfSpeech: string;
  exampleKorean: string;
  exampleEnglish: string;
}

export const koreanWords: KoreanWord[] = [
  { korean: "사랑", romanization: "sarang", english: "love", partOfSpeech: "noun", exampleKorean: "나는 너를 사랑해.", exampleEnglish: "I love you." },
  { korean: "감사합니다", romanization: "gamsahamnida", english: "thank you (formal)", partOfSpeech: "expression", exampleKorean: "도와주셔서 감사합니다.", exampleEnglish: "Thank you for helping me." },
  { korean: "안녕하세요", romanization: "annyeonghaseyo", english: "hello (formal)", partOfSpeech: "expression", exampleKorean: "안녕하세요, 처음 뵙겠습니다.", exampleEnglish: "Hello, nice to meet you." },
  { korean: "행복", romanization: "haengbok", english: "happiness", partOfSpeech: "noun", exampleKorean: "나는 행복을 원해.", exampleEnglish: "I want happiness." },
  { korean: "친구", romanization: "chingu", english: "friend", partOfSpeech: "noun", exampleKorean: "그는 내 친구야.", exampleEnglish: "He is my friend." },
  { korean: "먹다", romanization: "meokda", english: "to eat", partOfSpeech: "verb", exampleKorean: "나는 밥을 먹다.", exampleEnglish: "I eat rice." },
  { korean: "물", romanization: "mul", english: "water", partOfSpeech: "noun", exampleKorean: "물을 마시고 싶어요.", exampleEnglish: "I want to drink water." },
  { korean: "학교", romanization: "hakgyo", english: "school", partOfSpeech: "noun", exampleKorean: "나는 학교에 가요.", exampleEnglish: "I go to school." },
  { korean: "책", romanization: "chaek", english: "book", partOfSpeech: "noun", exampleKorean: "이 책은 재미있어요.", exampleEnglish: "This book is interesting." },
  { korean: "하다", romanization: "hada", english: "to do", partOfSpeech: "verb", exampleKorean: "숙제를 해야 해.", exampleEnglish: "I have to do homework." },
  { korean: "예쁘다", romanization: "yeppeuda", english: "to be pretty / beautiful", partOfSpeech: "adjective", exampleKorean: "그녀는 정말 예뻐요.", exampleEnglish: "She is really pretty." },
  { korean: "집", romanization: "jip", english: "house / home", partOfSpeech: "noun", exampleKorean: "나는 집에 있어요.", exampleEnglish: "I am at home." },
  { korean: "시간", romanization: "sigan", english: "time", partOfSpeech: "noun", exampleKorean: "시간이 없어요.", exampleEnglish: "I don't have time." },
  { korean: "가다", romanization: "gada", english: "to go", partOfSpeech: "verb", exampleKorean: "어디에 가요?", exampleEnglish: "Where are you going?" },
  { korean: "오다", romanization: "oda", english: "to come", partOfSpeech: "verb", exampleKorean: "언제 와요?", exampleEnglish: "When are you coming?" },
  { korean: "크다", romanization: "keuda", english: "to be big / large", partOfSpeech: "adjective", exampleKorean: "저 건물은 정말 커요.", exampleEnglish: "That building is really big." },
  { korean: "작다", romanization: "jakda", english: "to be small", partOfSpeech: "adjective", exampleKorean: "이 방은 너무 작아요.", exampleEnglish: "This room is too small." },
  { korean: "맛있다", romanization: "masitda", english: "to be delicious", partOfSpeech: "adjective", exampleKorean: "이 음식은 정말 맛있어요.", exampleEnglish: "This food is really delicious." },
  { korean: "좋다", romanization: "jota", english: "to be good / nice", partOfSpeech: "adjective", exampleKorean: "날씨가 좋아요.", exampleEnglish: "The weather is nice." },
  { korean: "많다", romanization: "manta", english: "to be many / much", partOfSpeech: "adjective", exampleKorean: "사람들이 많아요.", exampleEnglish: "There are many people." },
  { korean: "나라", romanization: "nara", english: "country / nation", partOfSpeech: "noun", exampleKorean: "어느 나라에서 왔어요?", exampleEnglish: "Which country are you from?" },
  { korean: "음악", romanization: "eumak", english: "music", partOfSpeech: "noun", exampleKorean: "음악을 들어요.", exampleEnglish: "I listen to music." },
  { korean: "날씨", romanization: "nalsi", english: "weather", partOfSpeech: "noun", exampleKorean: "오늘 날씨가 어때요?", exampleEnglish: "How is the weather today?" },
  { korean: "꿈", romanization: "kkum", english: "dream", partOfSpeech: "noun", exampleKorean: "나는 큰 꿈이 있어요.", exampleEnglish: "I have a big dream." },
  { korean: "바쁘다", romanization: "bappeuda", english: "to be busy", partOfSpeech: "adjective", exampleKorean: "요즘 너무 바빠요.", exampleEnglish: "I'm very busy these days." },
  { korean: "힘들다", romanization: "himdeulda", english: "to be difficult / exhausting", partOfSpeech: "adjective", exampleKorean: "오늘 하루가 정말 힘들었어요.", exampleEnglish: "Today was really exhausting." },
  { korean: "괜찮다", romanization: "gwaenchanta", english: "to be okay / fine", partOfSpeech: "adjective", exampleKorean: "괜찮아요?", exampleEnglish: "Are you okay?" },
  { korean: "모르다", romanization: "moreuda", english: "to not know", partOfSpeech: "verb", exampleKorean: "그것을 몰라요.", exampleEnglish: "I don't know that." },
  { korean: "알다", romanization: "alda", english: "to know", partOfSpeech: "verb", exampleKorean: "당신을 알고 있어요.", exampleEnglish: "I know you." },
  { korean: "보다", romanization: "boda", english: "to see / watch", partOfSpeech: "verb", exampleKorean: "영화를 봐요.", exampleEnglish: "I watch a movie." },
  { korean: "듣다", romanization: "deutda", english: "to listen / hear", partOfSpeech: "verb", exampleKorean: "음악을 들어요.", exampleEnglish: "I listen to music." },
  { korean: "말하다", romanization: "malhada", english: "to speak / say", partOfSpeech: "verb", exampleKorean: "한국어로 말해요.", exampleEnglish: "I speak in Korean." },
  { korean: "쓰다", romanization: "sseuda", english: "to write", partOfSpeech: "verb", exampleKorean: "편지를 써요.", exampleEnglish: "I write a letter." },
  { korean: "읽다", romanization: "ikda", english: "to read", partOfSpeech: "verb", exampleKorean: "책을 읽어요.", exampleEnglish: "I read a book." },
  { korean: "자다", romanization: "jada", english: "to sleep", partOfSpeech: "verb", exampleKorean: "일찍 자야 해요.", exampleEnglish: "I need to sleep early." },
  { korean: "일어나다", romanization: "ireonada", english: "to wake up / get up", partOfSpeech: "verb", exampleKorean: "아침에 일찍 일어나요.", exampleEnglish: "I wake up early in the morning." },
  { korean: "노래", romanization: "norae", english: "song", partOfSpeech: "noun", exampleKorean: "좋아하는 노래가 있어요?", exampleEnglish: "Do you have a favorite song?" },
  { korean: "영화", romanization: "yeonghwa", english: "movie / film", partOfSpeech: "noun", exampleKorean: "영화 보러 가요.", exampleEnglish: "Let's go watch a movie." },
  { korean: "여행", romanization: "yeohaeng", english: "travel / trip", partOfSpeech: "noun", exampleKorean: "여행을 좋아해요.", exampleEnglish: "I like to travel." },
  { korean: "음식", romanization: "eumsik", english: "food", partOfSpeech: "noun", exampleKorean: "한국 음식이 맛있어요.", exampleEnglish: "Korean food is delicious." },
  { korean: "돈", romanization: "don", english: "money", partOfSpeech: "noun", exampleKorean: "돈이 없어요.", exampleEnglish: "I don't have money." },
  { korean: "사람", romanization: "saram", english: "person / people", partOfSpeech: "noun", exampleKorean: "저 사람이 누구예요?", exampleEnglish: "Who is that person?" },
  { korean: "이름", romanization: "ireum", english: "name", partOfSpeech: "noun", exampleKorean: "이름이 뭐예요?", exampleEnglish: "What is your name?" },
  { korean: "생일", romanization: "saengil", english: "birthday", partOfSpeech: "noun", exampleKorean: "생일 축하해요!", exampleEnglish: "Happy birthday!" },
  { korean: "가족", romanization: "gajok", english: "family", partOfSpeech: "noun", exampleKorean: "가족이 소중해요.", exampleEnglish: "Family is precious." },
  { korean: "엄마", romanization: "eomma", english: "mom / mother", partOfSpeech: "noun", exampleKorean: "엄마, 사랑해요.", exampleEnglish: "Mom, I love you." },
  { korean: "아빠", romanization: "appa", english: "dad / father", partOfSpeech: "noun", exampleKorean: "아빠가 요리를 잘해요.", exampleEnglish: "Dad is good at cooking." },
  { korean: "봄", romanization: "bom", english: "spring (season)", partOfSpeech: "noun", exampleKorean: "봄에는 꽃이 피어요.", exampleEnglish: "Flowers bloom in spring." },
  { korean: "여름", romanization: "yeoreum", english: "summer", partOfSpeech: "noun", exampleKorean: "여름에 수영을 해요.", exampleEnglish: "I swim in summer." },
  { korean: "가을", romanization: "gaeul", english: "autumn / fall", partOfSpeech: "noun", exampleKorean: "가을에 단풍이 예뻐요.", exampleEnglish: "Autumn leaves are pretty." },
  { korean: "겨울", romanization: "gyeoul", english: "winter", partOfSpeech: "noun", exampleKorean: "겨울에 눈이 와요.", exampleEnglish: "It snows in winter." },
  { korean: "하늘", romanization: "haneul", english: "sky", partOfSpeech: "noun", exampleKorean: "하늘이 파래요.", exampleEnglish: "The sky is blue." },
  { korean: "바다", romanization: "bada", english: "sea / ocean", partOfSpeech: "noun", exampleKorean: "바다가 보고 싶어요.", exampleEnglish: "I want to see the ocean." },
  { korean: "산", romanization: "san", english: "mountain", partOfSpeech: "noun", exampleKorean: "산에 올라가요.", exampleEnglish: "I climb the mountain." },
  { korean: "빠르다", romanization: "ppareuda", english: "to be fast / quick", partOfSpeech: "adjective", exampleKorean: "그는 정말 빨라요.", exampleEnglish: "He is really fast." },
  { korean: "느리다", romanization: "neurida", english: "to be slow", partOfSpeech: "adjective", exampleKorean: "거북이는 느려요.", exampleEnglish: "Turtles are slow." },
  { korean: "쉽다", romanization: "swipda", english: "to be easy", partOfSpeech: "adjective", exampleKorean: "이 문제는 쉬워요.", exampleEnglish: "This problem is easy." },
  { korean: "어렵다", romanization: "eoryeopda", english: "to be difficult / hard", partOfSpeech: "adjective", exampleKorean: "한국어는 어려워요.", exampleEnglish: "Korean is difficult." },
  { korean: "재미있다", romanization: "jaemiitda", english: "to be fun / interesting", partOfSpeech: "adjective", exampleKorean: "이 게임은 재미있어요.", exampleEnglish: "This game is fun." },
  { korean: "심심하다", romanization: "simsimhada", english: "to be bored", partOfSpeech: "adjective", exampleKorean: "집에서 심심해요.", exampleEnglish: "I'm bored at home." },
  { korean: "피곤하다", romanization: "pigonhada", english: "to be tired", partOfSpeech: "adjective", exampleKorean: "오늘 너무 피곤해요.", exampleEnglish: "I'm very tired today." },
  { korean: "배고프다", romanization: "baegopuda", english: "to be hungry", partOfSpeech: "adjective", exampleKorean: "배고파요, 밥 먹어요.", exampleEnglish: "I'm hungry, let's eat." },
  { korean: "기쁘다", romanization: "gippeuda", english: "to be glad / joyful", partOfSpeech: "adjective", exampleKorean: "만나서 기뻐요.", exampleEnglish: "I'm glad to meet you." },
  { korean: "슬프다", romanization: "seulpeuda", english: "to be sad", partOfSpeech: "adjective", exampleKorean: "영화가 슬펐어요.", exampleEnglish: "The movie was sad." },
  { korean: "멋있다", romanization: "meositda", english: "to be cool / stylish", partOfSpeech: "adjective", exampleKorean: "그 옷이 정말 멋있어요.", exampleEnglish: "Those clothes are really cool." },
  { korean: "귀엽다", romanization: "gwiyeopda", english: "to be cute", partOfSpeech: "adjective", exampleKorean: "강아지가 귀여워요.", exampleEnglish: "The puppy is cute." },
  { korean: "배우다", romanization: "baeuda", english: "to learn", partOfSpeech: "verb", exampleKorean: "한국어를 배우고 있어요.", exampleEnglish: "I am learning Korean." },
  { korean: "가르치다", romanization: "gareuchida", english: "to teach", partOfSpeech: "verb", exampleKorean: "선생님이 수학을 가르쳐요.", exampleEnglish: "The teacher teaches math." },
  { korean: "만들다", romanization: "mandeulda", english: "to make / create", partOfSpeech: "verb", exampleKorean: "케이크를 만들어요.", exampleEnglish: "I make a cake." },
  { korean: "찾다", romanization: "chatda", english: "to find / look for", partOfSpeech: "verb", exampleKorean: "열쇠를 찾아요.", exampleEnglish: "I'm looking for my keys." },
  { korean: "생각하다", romanization: "saenggakhada", english: "to think", partOfSpeech: "verb", exampleKorean: "열심히 생각해요.", exampleEnglish: "I think hard." },
  { korean: "이해하다", romanization: "ihaehada", english: "to understand", partOfSpeech: "verb", exampleKorean: "당신을 이해해요.", exampleEnglish: "I understand you." },
  { korean: "기억하다", romanization: "gieokhada", english: "to remember", partOfSpeech: "verb", exampleKorean: "그날을 기억해요.", exampleEnglish: "I remember that day." },
  { korean: "잊다", romanization: "itda", english: "to forget", partOfSpeech: "verb", exampleKorean: "이름을 잊어버렸어요.", exampleEnglish: "I forgot the name." },
  { korean: "시작하다", romanization: "sijakhada", english: "to start / begin", partOfSpeech: "verb", exampleKorean: "공부를 시작해요.", exampleEnglish: "I start studying." },
  { korean: "끝나다", romanization: "kkeutnada", english: "to end / finish", partOfSpeech: "verb", exampleKorean: "수업이 끝났어요.", exampleEnglish: "The class is over." },
  { korean: "기다리다", romanization: "gidarida", english: "to wait", partOfSpeech: "verb", exampleKorean: "버스를 기다려요.", exampleEnglish: "I wait for the bus." },
  { korean: "도와주다", romanization: "dowajuda", english: "to help", partOfSpeech: "verb", exampleKorean: "나를 도와줄 수 있어요?", exampleEnglish: "Can you help me?" },
  { korean: "주다", romanization: "juda", english: "to give", partOfSpeech: "verb", exampleKorean: "선물을 줘요.", exampleEnglish: "I give a gift." },
  { korean: "받다", romanization: "batda", english: "to receive / get", partOfSpeech: "verb", exampleKorean: "편지를 받았어요.", exampleEnglish: "I received a letter." },
  { korean: "사다", romanization: "sada", english: "to buy", partOfSpeech: "verb", exampleKorean: "사과를 사요.", exampleEnglish: "I buy an apple." },
  { korean: "달리다", romanization: "dallida", english: "to run", partOfSpeech: "verb", exampleKorean: "공원에서 달려요.", exampleEnglish: "I run in the park." },
  { korean: "걷다", romanization: "geotda", english: "to walk", partOfSpeech: "verb", exampleKorean: "천천히 걸어요.", exampleEnglish: "I walk slowly." },
  { korean: "웃다", romanization: "utda", english: "to laugh / smile", partOfSpeech: "verb", exampleKorean: "당신이 웃으면 예뻐요.", exampleEnglish: "You look pretty when you smile." },
  { korean: "울다", romanization: "ulda", english: "to cry", partOfSpeech: "verb", exampleKorean: "왜 울어요?", exampleEnglish: "Why are you crying?" },
  { korean: "노력하다", romanization: "noryeokhada", english: "to make an effort / try hard", partOfSpeech: "verb", exampleKorean: "더 노력할게요.", exampleEnglish: "I will try harder." },
  { korean: "포기하다", romanization: "pogihada", english: "to give up", partOfSpeech: "verb", exampleKorean: "절대 포기하지 마세요.", exampleEnglish: "Never give up." },
  { korean: "믿다", romanization: "mitda", english: "to believe / trust", partOfSpeech: "verb", exampleKorean: "당신을 믿어요.", exampleEnglish: "I trust you." },
  { korean: "약속", romanization: "yakso", english: "promise / appointment", partOfSpeech: "noun", exampleKorean: "약속을 지켜요.", exampleEnglish: "I keep my promise." },
  { korean: "희망", romanization: "huimang", english: "hope", partOfSpeech: "noun", exampleKorean: "희망을 잃지 마세요.", exampleEnglish: "Don't lose hope." },
  { korean: "용기", romanization: "yonggi", english: "courage", partOfSpeech: "noun", exampleKorean: "용기를 내세요.", exampleEnglish: "Have courage." },
  { korean: "성공", romanization: "seonggong", english: "success", partOfSpeech: "noun", exampleKorean: "성공을 축하해요.", exampleEnglish: "Congratulations on your success." },
  { korean: "건강", romanization: "geongang", english: "health", partOfSpeech: "noun", exampleKorean: "건강이 최고예요.", exampleEnglish: "Health is the best." },
  { korean: "평화", romanization: "pyeonghwa", english: "peace", partOfSpeech: "noun", exampleKorean: "세계 평화를 원해요.", exampleEnglish: "I want world peace." },
  { korean: "미래", romanization: "mirae", english: "future", partOfSpeech: "noun", exampleKorean: "밝은 미래를 꿈꿔요.", exampleEnglish: "I dream of a bright future." },
];

export function getWordOfTheDay(): KoreanWord {
  const start = new Date(2024, 0, 1);
  const now = new Date();
  const daysSinceStart = Math.floor(
    (now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)
  );
  return koreanWords[daysSinceStart % koreanWords.length];
